# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: mostakimsakib0/mostakimsakib0.github.io
  branch: main

media_folder: /static/uploads
public_folder: /uploads

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "image", widget: "image", required: false, hint: "Upload a featured image for the blog post" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Body", name: "body", widget: "markdown", hint: "Use the image button in the toolbar to upload & insert images in the post" }

  - name: "achievements"
    label: "Achievements"
    folder: "content/achievements"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "image", widget: "image", required: false }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    files:
      - label: "About"
        name: "about"
        file: "content/about/_index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Featured Image", name: "image", widget: "image", required: false }
          - { label: "Description", name: "description", widget: "string", required: false }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Projects"
        name: "projects"
        file: "content/projects/_index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Featured Image", name: "image", widget: "image", required: false }
          - { label: "Description", name: "description", widget: "string", required: false }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Contact"
        name: "contact"
        file: "content/contact/_index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Featured Image", name: "image", widget: "image", required: false }
          - { label: "Description", name: "description", widget: "string", required: false }
          - { label: "Body", name: "body", widget: "markdown" }
